### ISSUE TITLE
Shifted Data

### ISSUE THREAD

**Issue by whaleshark16** [USCOVIDpolicy/COVID-19-US-State-Policy-Database#1]
Hi ! Thank you for all of your hard work tracking all of this data!

It looks like the data may have inadvertently gotten shifted for the last several states for some of the columns. For instance, Report deaths by race/ethnicity has dates in the column for the last 4 states.

**Comment by KristenNocka** [comment]
Thank you so much for bringing this to my attention! The issue has been fixed.
