### ISSUE TITLE
Typo in 08/05 update

### ISSUE THREAD

**Issue by guzhiling** [USCOVIDpolicy/COVID-19-US-State-Policy-Database#12]
Thank you for the recent updates and the added variables! They are extremely useful!

In the 08-05 updated dataset, there is a typo. See in the figure, extra **12**.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/37173670/89587547-70610a80-d807-11ea-8515-4196dd343b3f.png">

**Comment by USCOVIDpolicy** [comment]
Thank you! This will be corrected in the update I put out on Monday.

**Comment by USCOVIDpolicy** [comment]
The update is live.
