### ISSUE TITLE
US State Policy Name Consistency

### ISSUE THREAD

**Issue by dusty-turner** [USCOVIDpolicy/COVID-19-US-State-Policy-Database#13]
Hi team, 

Thanks so much for your efforts and work consolidating this information and making it publicly available.  

I do a check and a pull of the data every day to download the latest update.  I noticed that sometimes the names of the files are inconsistent which makes it hard to automate this. In particular, sometimes you use a 2 digit month vs a 1 digit month.  For example "08" vs "8" for August.

I was wondering if you would mind standardizing the naming convention to help those who look at this data on a regular basis?

Thanks again for the good work and what you do to help fight the spread of COVID!
Dusty

**Comment by USCOVIDpolicy** [comment]
Can do. Would it help to edit the previous versions? I apologize for the naming issue.

**Comment by dusty-turner** [comment]
Sorry for my delay in responding here.  My email filter hid this from me.  It would be nice if you edited the previous version.  

Again, I want to reiterate how grateful we are for your work!

**Comment by USCOVIDpolicy** [comment]
Thank you for helping us build a better database. I took over maintaining the database at the end of July so all input helps us so much. I will remove the 0's.
