### ISSUE TITLE
Data missing: Florida bar reopening

### ISSUE THREAD

**Issue by GabrielLewis4** [USCOVIDpolicy/COVID-19-US-State-Policy-Database#14]
In this dataset, bars in Florida are listed as (re-)closing on 6/26/20, with no subsequent reopening. However, it appears that Florida bars reopened without restrictions on  9/25/2020:

https://www.msn.com/en-us/news/us/florida-reopens-bars-and-restaurants-with-no-restrictions/ar-BB19qR3Z

Ps. this is a very helpful dataset, thanks!

**Comment by USCOVIDpolicy** [comment]
Thank you for your note and for pointing this out! We will review Florida reopening documents to confirm that bars reopened on 9/25 and update the database accordingly.
