### ISSUE TITLE
Utah mask policies

### ISSUE THREAD

**Issue by corbinq** [USCOVIDpolicy/COVID-19-US-State-Policy-Database#2]
Hi, Thanks for the great work putting together this data!  I think the mask policy entry for Utah is off.  Utah's universal mask policy began on June 27 (https://www.ksl.com/article/46772675/salt-lake-county-extends-mask-order-through-august-salt-lake-chamber-asks-for-statewide-order).  The current CUSP data set indicates that Utah implemented a universal mask policy starting in April.

**Comment by KristenNocka** [comment]
Thank you so much for reaching out! Utah's governor issued a directive on April 10th that directed every individual in Utah to wear a face covering in any public place of accommodation where social distancing isn't possible. I've attached the order below. I'm glad you are finding the data useful! 

[UT 2020.04.10 facemask.pdf](https://github.com/KristenNocka/COVID-19-US-State-Policy-Database/files/4884954/UT.2020.04.10.facemask.pdf)

**Comment by corbinq** [comment]
Hi, Thanks for sharing the source document. This looks like a safer-at-home
order, which instructs Utah residents to wear masks in public places
among other things. However, it only lasted from April 10 through May 1.

If possible, I think it would be useful to separate safer-at-home orders
that include face-covering guidelines from more specific face-covering
mandates, particularly in cases where the safer-at-home orders expired.

**Comment by rscheckman83** [comment]
Thank you for the suggestion. We are coding for when facemasks are first required by the state. In this case, it happened in the safer-at-home order. We will add a note about Utah to our notes page on the next update so that it is clear to other users of the database.
