### ISSUE TITLE
Data Issue: New Mexico Date of Relaxing Shelter in Place 

### ISSUE THREAD

**Issue by guzhiling** [USCOVIDpolicy/COVID-19-US-State-Policy-Database#3]
In the [latest update (07/16)](https://github.com/KristenNocka/COVID-19-US-State-Policy-Database/blob/master/COVID-19%20US%20state%20policy%20database%207_16_2020.xlsx), the date of NM relaxing shelter in place seems incorrect, see the screenshot below.

<img width="228" alt="Screen Shot 2020-07-17 at 2 06 28 PM" src="https://user-images.githubusercontent.com/37173670/87822371-f60c1e80-c836-11ea-930d-05c0285c096e.png">

In the [data (07/15)](https://github.com/KristenNocka/COVID-19-US-State-Policy-Database/blob/master/COVID-19%20US%20state%20policy%20database%207_15_2020.xlsx), it showed 6/30/2020.

**Comment by rscheckman83** [comment]
This should be resolved in the current data from 7/24/2020.
